# Generated by Django 4.2.1 on 2023-06-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id_estado_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_alumno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMatricula',
            fields=[
                ('id_estado_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_matricula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListaAsignatura',
            fields=[
                ('id_lista_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista_asignatura', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCurso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=255)),
                ('s_nombre', models.CharField(blank=True, max_length=255)),
                ('appaterno', models.CharField(max_length=255)),
                ('apmaterno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=255)),
                ('telefono_fijo', models.BigIntegerField()),
                ('celular', models.BigIntegerField()),
                ('email', models.CharField(max_length=255, null=True)),
                ('id_direccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnotacion',
            fields=[
                ('id_tipo_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_anotacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoApoderado',
            fields=[
                ('id_tipo_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_apoderado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id_tipo_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_asistencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_curso', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.persona')),
                ('estudiante_prioritario', models.BooleanField(null=True)),
                ('enfermedad_cronica', models.CharField(max_length=255, null=True)),
                ('seguro_escolar_particular', models.CharField(max_length=255, null=True)),
                ('discapacidad_fisica', models.CharField(max_length=255, null=True)),
                ('evaluacion_profesional', models.BooleanField(null=True)),
                ('colegio_procedencia', models.CharField(max_length=255, null=True)),
                ('razon_cambio_colegio', models.CharField(max_length=255, null=True)),
                ('medio', models.CharField(max_length=255, null=True)),
                ('pie', models.BooleanField(null=True)),
                ('id_estado_alumno', models.ForeignKey(db_column='id_estado_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.estadoalumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('run', models.ForeignKey(db_column='run', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.persona')),
                ('grado_academico', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('mencion', models.CharField(max_length=50)),
                ('magister', models.CharField(max_length=50, null=True)),
                ('doctorado', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('run', models.ForeignKey(db_column='run', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.persona')),
                ('profesion', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('nivel_academico', models.CharField(max_length=255)),
                ('vive_con_alumno', models.BooleanField()),
                ('id_tipo_apoderado', models.ForeignKey(db_column='id_tipo_apoderado', on_delete=django.db.models.deletion.CASCADE, to='core.tipoapoderado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('id_estado_usuario', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.estadousuario')),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Código Curso')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='core.jornada', verbose_name='Tipo Jornada')),
                ('id_lista_curso', models.ForeignKey(db_column='id_lista_curso', on_delete=django.db.models.deletion.CASCADE, to='core.listacurso', verbose_name='Listas de Cursos')),
                ('id_tipo_curso', models.ForeignKey(db_column='id_tipo_curso', on_delete=django.db.models.deletion.CASCADE, to='core.tipocurso', verbose_name='Tipo Curso')),
                ('profesor_jefe', models.ForeignKey(db_column='run_profesor_jefe', on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('id_lista_asignatura', models.ForeignKey(db_column='id_lista_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.listaasignatura')),
                ('run_profesor', models.ForeignKey(db_column='run_profesor', on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAlumno',
            fields=[
                ('id_responsable_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_parentesco', models.ForeignKey(db_column='id_parentesco', on_delete=django.db.models.deletion.CASCADE, to='core.parentesco')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='set_run_alumno', to='core.alumno')),
                ('run_responsable', models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.CASCADE, related_name='set_id_responsable', to='core.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('descripcion_nota', models.CharField(max_length=50)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso_matricula', models.ForeignKey(db_column='id_curso_matricula', on_delete=django.db.models.deletion.CASCADE, related_name='set_curso_matricula', to='core.listacurso')),
                ('id_estado_matricula', models.ForeignKey(db_column='id_estado_matricula', on_delete=django.db.models.deletion.CASCADE, to='core.estadomatricula')),
                ('id_ultimo_curso_aprobado', models.ForeignKey(db_column='id_ultimo_curso_aprobado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_ultimo_curso_aprobado', to='core.listacurso')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id_grupo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familiar', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('parentesco', models.CharField(max_length=255)),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRepetido',
            fields=[
                ('id_curso_repetido', models.AutoField(primary_key=True, serialize=False)),
                ('anno_repitencia', models.IntegerField()),
                ('id_lista_curso', models.ForeignKey(db_column='id_lista_curso', on_delete=django.db.models.deletion.CASCADE, to='core.listacurso')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaCurso',
            fields=[
                ('id_asistencia_curso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('id_tipo_asistencia', models.ForeignKey(db_column='id_tipo_asistencia', on_delete=django.db.models.deletion.PROTECT, to='core.tipoasistencia')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('anotacion', models.CharField(max_length=200)),
                ('fecha_anotacion', models.DateField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.PROTECT, to='core.asignatura')),
                ('id_tipo_anotacion', models.ForeignKey(db_column='id-tipo_anotación', on_delete=django.db.models.deletion.PROTECT, to='core.tipoanotacion')),
                ('run_alumno', models.ForeignKey(db_column='run_alumno', on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
            ],
        ),
    ]
