# Generated by Django 4.2 on 2023-05-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoAsignatura',
            fields=[
                ('id_alumno_asignatura', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alumno_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anotaciones',
            fields=[
                ('id_anotación', models.AutoField(primary_key=True, serialize=False)),
                ('descripción_anotación', models.CharField(max_length=1000)),
                ('run', models.IntegerField()),
                ('id_persona', models.IntegerField()),
            ],
            options={
                'db_table': 'anotaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApoderadoAlumno',
            fields=[
                ('id_apod_alum', models.AutoField(primary_key=True, serialize=False)),
                ('vive_con_alumno', models.IntegerField()),
            ],
            options={
                'db_table': 'apoderado_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=50)),
                ('cantidad_de_horas', models.IntegerField()),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asistencia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('descripción_nota', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CobroEstudiantil',
            fields=[
                ('id_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_pago', models.DateField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'cobro_estudiantil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colegio', models.CharField(max_length=50)),
                ('representante_legal', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'colegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('cantidad_matricula', models.IntegerField()),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoRepetido',
            fields=[
                ('id_curso_repetido', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_curso_repetido', models.CharField(max_length=50, verbose_name='Curso Reprobado')),
                ('anno_repitencia', models.IntegerField(verbose_name='Año de Repitencia')),
            ],
            options={
                'db_table': 'curso_repetido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=25)),
                ('numero', models.CharField(blank=True, max_length=9, null=True)),
                ('depto', models.IntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id_estado_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_alumno', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_usuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id_gr_fam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('parentesco', models.CharField(max_length=25)),
                ('id_matricula', models.IntegerField()),
            ],
            options={
                'db_table': 'grupo_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('curso_matricula', models.CharField(max_length=50)),
                ('colegio_procedencia', models.CharField(max_length=50)),
                ('ultimo_curso_aprobado', models.CharField(max_length=50)),
                ('anno_curso_aprobado', models.IntegerField()),
                ('razon_cambio_colegio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.IntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_nombre', models.CharField(max_length=30)),
                ('s_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('app_paterno', models.CharField(max_length=30)),
                ('app_materno', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('run', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('telefono_fijo', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAnotacion',
            fields=[
                ('id_tipo_anotacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_anotacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_anotacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoApoderado',
            fields=[
                ('id_tipo_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_apoderado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='listaCursos',
            fields=[
                ('id_lista_curso', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Lista Curso')),
                ('nombre_curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.persona')),
                ('grado_academico', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('mencion', models.CharField(max_length=50)),
                ('magister', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorado', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('etnia', models.CharField(blank=True, max_length=30, null=True)),
                ('estudiante_prioritario', models.IntegerField()),
                ('enfermedad_cronica', models.CharField(blank=True, max_length=50, null=True)),
                ('seguro_escolar_particular', models.CharField(blank=True, max_length=50, null=True)),
                ('run', models.OneToOneField(db_column='run', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='alumno_run_set', serialize=False, to='core.persona')),
                ('discapacidad_fisica', models.CharField(blank=True, max_length=50, null=True)),
                ('pie', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.persona')),
                ('profesion', models.CharField(max_length=40)),
                ('ocupación', models.CharField(max_length=40)),
                ('nivel_academico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.persona')),
                ('grado_academico', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('mencion', models.CharField(max_length=50)),
                ('magister', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
    ]
