# Generated by Django 4.2 on 2023-05-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursorepetido',
            options={'managed': True},
        ),
    ]
