# Generated by Django 4.2.1 on 2023-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cursorepetido_nombre_curso_repetido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorepetido',
            name='id_lista_curso',
            field=models.IntegerField(verbose_name='Id lista curso'),
        ),
    ]
