# Generated by Django 4.2.1 on 2023-05-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cursorepetido_id_lista_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorepetido',
            name='id_lista_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.listacursos', verbose_name='Nombre Curso'),
        ),
    ]
